# Generated by Django 4.2.6 on 2023-10-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("featura", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="downvotes", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post", name="upvotes", field=models.IntegerField(default=0),
        ),
    ]
